apiVersion: v1
kind: Service
metadata:
  name: impocali-service
  labels:
    app: impocali
spec:
  type: LoadBalancer
  selector:
    app: impocali
  ports:
    - protocol: TCP
      port: 80 # Puerto público (externo)
      targetPort: 8000
