apiVersion: v1
kind: Service
metadata:
  name: impocali-service
  labels:
    app: impocali
spec:
  type: LoadBalancer # Esto permite obtener una IP pública accesible
  selector:
    app: impocali # Debe coincidir con el label del deployment
  ports:
    - protocol: TCP
      port: 80 # Puerto accesible externamente
      targetPort: 5000 # Puerto donde tu app Flask (Gunicorn) escucha internamente
